### ISSUE TITLE
Workspaces goes blank in the overview

### ISSUE THREAD

**Issue by soumyaDghosh** [axxapy/gnome-ui-tune#30] opened 2022-09-29 08:39 UTC
This is the same issue as described in #29, I tested that in a clean installation of ubuntu22.04, problem is same. 

![Screenshot from 2022-09-25 12-35-11](https://user-images.githubusercontent.com/72045785/192981972-43cd9e70-10c2-4fd9-823e-485018162b28.png)

And this is from Ubuntu 22.10 kinetic kudu

![Screenshot from 2022-09-29 09-22-22](https://user-images.githubusercontent.com/72045785/192982255-e95cc945-f3e8-46e3-bca2-803593995a22.png)

**Comment by axxapy** [comment] 2022-09-30 23:25
I can not reproduce it in virtual machine, so, you have 3 options:

0. check that you have latest version of extension installed
1. disable "hide search", open dashboard (it will fix itself) and enable this option back (do same on each reboot)
2. disable "hide search" completely
3. Investigate issue on your own and send a PR. Extension files are located at `~/.local/share/gnome-shell/extensions/gnome-ui-tune@itstime.tech`. This particular line is responsible for hiding search: https://github.com/axxapy/gnome-ui-tune/blob/master/src/modHideSearchInput.js#L15. You may try increasing delay, for instance (one line above) from 50 to 500 (it's in ms)

**Comment by soumyaDghosh** [comment] 2022-10-05 15:05
I got the issue. I use hard-disk-drive, with an average of 150MB/s of RW speed. The virtual machine is in the same hdd. So, may be the dash-to-dock takes more time to initialize. 500ms mostly solves the issue.

**Comment by martindmtrv** [comment] 2022-11-16 00:11
For the longest time I thought this was a Dash2Dock issue, but seems like it was caused by some clash here.

I had the same issue and switching it to 500ms seems to fix for me as well. 

If I ever get in this weird state, typing in the overview and then returning to the overview (pressing esc) seems to fix it right away without needing to dive in the settings. I wonder if there's any way we can "wait" for Dash2Dock to load up instead of using an arbitrary wait time though

**Comment by ezoterikwa** [comment] 2023-01-25 15:38
Exactly the same damn thing, but only when turning on the computer/logging into a session. And this bug happens randomly and every once in a while. It helps to turn off and then turn on the extension. Does anyone know how to make this extension restart automatically when you turn it on, or just disable/enable all extensions?
![Снимок экрана от 2023-01-25 17-31-25](https://user-images.githubusercontent.com/106447794/214606840-664390f4-023d-42b4-b5f3-c54756e7b59a.png)

**Comment by ddnexus** [comment] 2023-04-12 03:22
For me it fixes it with 150ms. The only problem is changing it again at every update.

@axxapy Couldn't we just have a fixed default delay bigger than 50ms? For example 250ms? 
That would solve the issue without actually having to investigate anything nor complicate the code.

**Comment by axxapy** [comment] 2023-04-13 01:55
> For me it fixes it with 150ms. The only problem is changing it again at every update.
> 
> @axxapy Couldn't we just have a fixed default delay bigger than 50ms? For example 250ms? That would solve the issue without actually having to investigate anything nor complicate the code.

I mean.. I really feel bad about that kind of hacky solutions with delay... But lets give it a shot.
Updated to half-a-second. Released. It will wait 500ms now.

**Comment by ddnexus** [comment] 2023-04-13 05:11
Thank you!

> I really feel bad about that kind of hacky solutions with delay...

So why there was a 50ms delay anyway? 

Btw, the resizing in 2 steps looks more noticeable now with 500ms. I would have used a shorter delay that would probably have the same result with half the delay, however, I think nobody will notice it.

**Comment by axxapy** [comment] 2023-10-17 19:03
Fixed in the latest release (exclusively for Gnome 45)

**Closed as completed by axxapy** 2023-10-17 19:03 UTC
