### ISSUE TITLE
2x thumbnail size causes animation stutter

### ISSUE THREAD

**Issue by eobet** [axxapy/gnome-ui-tune#34] opened 2023-07-14 15:24 UTC
After a reboot (may be other triggers as well), zooming out to see all workspaces for the first time causes a stutter right at the end of the animation. It's as if the zoom wants to go all the way, but then jumps back at the last moment due to the increased size... then it won't happen again until you put the computer to sleep or reboot.

Anyone else seeing that?

**Comment by Zatan16** [comment] 2023-09-18 14:47
Maybe post a video, that may help others visualize/understand it better.

**Comment by Zatan16** [comment] 2023-09-18 14:56
Here is the video I recorded: 
[Screencast from 2023-09-18 20-24-54.webm](https://github.com/axxapy/gnome-ui-tune/assets/79738479/21c49950-1b82-4909-80a1-38d4312cdac1)

**Comment by Zatan16** [comment] 2023-09-20 01:33
I may have a potential fix. The issue is that the search bar takes 500 ms before disappearing and causing the animation to stutter. It is because of Dash to Dock. If Dash to Dock and this extension try to load at the same time, it will break the overview so this extension adds a 500 ms delay. We can try decreasing it to 50ms and it still works. It was supposed to be 50 ms as written in the comments before the piece of code.

**Comment by axxapy** [comment] 2023-10-17 18:59
Should be fixed in the latest release (only for gnome 45)

**Closed as completed by axxapy** 2023-10-17 18:59 UTC
