### ISSUE TITLE
Multi-monitor support

### ISSUE THREAD

**Issue by dkuehn-cbre** [axxapy/gnome-ui-tune#2] opened 2021-04-13 07:15 UTC
Thanks your for this extension. I noticed that the workspace overview on another screen is not increased. Can you take care of this as well?

**Comment by axxapy** [comment] 2021-04-13 07:58
I do not have access to second monitor at the moment.
But will have in about a week or so (moving to a new house) and will definitely take a look.

**Comment by nariox** [comment] 2021-04-14 22:10
Since #2 was closed, I am assuming all multi-monitor issues are going to be tracked here?

One thing I have observed is that my overview on my main monitor is that of the secondary monitor, and the one in my secondary monitor is also the one from the secondary monitor (but small).

That said, I am really thankful for this extension, as it really increases the usability for my old man's eyes when I am running my laptop undocked.

**Comment by axxapy** [comment] 2021-04-15 06:38
What do you mean #2 was closed? You meant #4?

> I am assuming all multi-monitor issues are going to be tracked here?

Yes, I have not debugged this extension with multi-monitor setup yet and going do that in the scope of this issue.

>One thing I have observed...

If you could, please attach screenshots. It may help me to understand the issue and may be even fix it before I get access to the second monitor.

**Comment by nariox** [comment] 2021-04-15 13:10
Yes, sorry, #4 was closed. I got them mixed.

![extensionshot](https://user-images.githubusercontent.com/1010760/114873855-baa07f80-9dc9-11eb-9006-f74217d03a30.png)

Above is my screenshot. It shows:
1- The overview in the secondary monitor is small (OP's reason for issue)
2- The contents of the overview are duplicated and only show the secondary monitor's content (my? report)
Notice that I have enabled workspaces on both monitors, instead of the default behavior.

**Comment by axxapy** [comment] 2021-04-25 23:00
Okay, I have fixed thumbnails size & background on the second monitor and published new release.
- Release: https://github.com/axxapy/gnome-ui-tune/releases/tag/v1.2.0
- extensions.gnome.org review: https://extensions.gnome.org/review/24142

You can either install in manually or wait for review to be done & update via standard tools

---

>  2- The contents of the overview are duplicated and only show the secondary monitor's content (my? report)

That is extremely strange as it does not happen to me (my second monitor is on the top):
![Screenshot from 2021-04-25 18-58-02](https://user-images.githubusercontent.com/3088476/116012402-413e3380-a5f8-11eb-8353-edfbb29760cd.png)

Could you please:
 - try to disable all extensions except this one and verify that this is still happening
 - if yes (I dont think so), create separate bug 

Thank you

**Closed as completed** 2021-04-25 23:02 UTC
Labels: bug

**Comment by nariox** [comment] 2021-04-26 00:35
I can confirm 1.2.0 fixes the duplicated overviews! :)
Thanks!
